CREATE TABLE IF NOT EXISTS Location (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Route (
    id INTEGER PRIMARY KEY,
    from_id INTEGER NOT NULL,
    to_id INTEGER NOT NULL,
    cost INTEGER
);

CREATE TABLE IF NOT EXISTS Problem (
    id INTEGER PRIMARY KEY,
    from_id INTEGER NOT NULL,
    to_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Solution (
    problem_id INTEGER PRIMARY KEY,
    cost INTEGER NOT NULL
);